# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GANgineer_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class Ui_GANgineer(object):
    flag_list = ["listView_input", "listView_input2", "listView_input3"]

    def setupUi(self, GANgineer):
        GANgineer.setWindowIcon(QIcon('./image/GANgineer.png'))
        GANgineer.setObjectName("GANgineer")
        GANgineer.resize(891, 801)
        GANgineer.setStyleSheet("background-cololr : rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(GANgineer)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 861, 741))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(240, 248, 255);")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView_input = QtWidgets.QListView(self.tab)
        self.listView_input.setGeometry(QtCore.QRect(100, 50, 161, 251))
        self.listView_input.setObjectName("listView_input")
        self.label_inImage = QtWidgets.QLabel(self.tab)
        self.label_inImage.setGeometry(QtCore.QRect(80, 370, 200, 200))
        self.label_inImage.setAutoFillBackground(False)
        self.label_inImage.setText("")
        self.label_inImage.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_inImage.setScaledContents(True)
        self.label_inImage.setObjectName("label_inImage")
        self.label_outImage = QtWidgets.QLabel(self.tab)
        self.label_outImage.setGeometry(QtCore.QRect(560, 370, 200, 200))
        self.label_outImage.setText("")
        self.label_outImage.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_outImage.setScaledContents(True)
        self.label_outImage.setObjectName("label_outImage")
        self.listView_output = QtWidgets.QListView(self.tab)
        self.listView_output.setGeometry(QtCore.QRect(580, 50, 161, 251))
        self.listView_output.setObjectName("listView_output")
        self.label_outResult = QtWidgets.QLabel(self.tab)
        self.label_outResult.setGeometry(QtCore.QRect(160, 620, 531, 51))
        self.label_outResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_outResult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                           "font: 75 14pt \"Arial\";")
        self.label_outResult.setLineWidth(0)
        self.label_outResult.setObjectName("label_outResult")
        self.pushButton_detect = QtWidgets.QPushButton(self.tab)
        self.pushButton_detect.setGeometry(QtCore.QRect(370, 540, 93, 28))
        self.pushButton_detect.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                             "font: 75 9pt \"Arial\";\n"
                                             "color: rgb(7, 7, 7);")
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.pushButton_inOpen = QtWidgets.QPushButton(self.tab)
        self.pushButton_inOpen.setGeometry(QtCore.QRect(100, 310, 81, 28))
        self.pushButton_inOpen.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                             "font: 75 9pt \"Arial\";\n"
                                             "color: rgb(7, 7, 7);")
        self.pushButton_inOpen.setObjectName("pushButton_inOpen")
        self.pushButton_inDelete = QtWidgets.QPushButton(self.tab)
        self.pushButton_inDelete.setGeometry(QtCore.QRect(180, 310, 81, 28))
        self.pushButton_inDelete.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                               "font: 75 9pt \"Arial\";\n"
                                               "color: rgb(7, 7, 7);")
        self.pushButton_inDelete.setObjectName("pushButton_inDelete")
        self.pushButton_outDelete = QtWidgets.QPushButton(self.tab)
        self.pushButton_outDelete.setGeometry(QtCore.QRect(660, 310, 81, 28))
        self.pushButton_outDelete.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                                "font: 75 9pt \"Arial\";\n"
                                                "color: rgb(7, 7, 7);")
        self.pushButton_outDelete.setObjectName("pushButton_outDelete")
        self.pushButton_outSave = QtWidgets.QPushButton(self.tab)
        self.pushButton_outSave.setGeometry(QtCore.QRect(580, 310, 81, 28))
        self.pushButton_outSave.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                              "font: 75 9pt \"Arial\";\n"
                                              "color: rgb(7, 7, 7);")
        self.pushButton_outSave.setObjectName("pushButton_outSave")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(580, 30, 101, 16))
        self.label_4.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(100, 30, 101, 16))
        self.label_45.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_45.setObjectName("label_45")
        self.label_48 = QtWidgets.QLabel(self.tab)
        self.label_48.setGeometry(QtCore.QRect(370, 430, 81, 61))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(370, 140, 81, 61))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_outSave.raise_()
        self.listView_input.raise_()
        self.label_inImage.raise_()
        self.label_outImage.raise_()
        self.listView_output.raise_()
        self.label_outResult.raise_()
        self.pushButton_detect.raise_()
        self.pushButton_inOpen.raise_()
        self.pushButton_inDelete.raise_()
        self.pushButton_outDelete.raise_()
        self.label_4.raise_()
        self.label_45.raise_()
        self.label_48.raise_()
        self.label_23.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_detect2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_detect2.setGeometry(QtCore.QRect(370, 540, 93, 28))
        self.pushButton_detect2.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                              "font: 75 9pt \"Arial\";\n"
                                              "color: rgb(7, 7, 7);")
        self.pushButton_detect2.setObjectName("pushButton_detect2")
        self.label_inImage2 = QtWidgets.QLabel(self.tab_2)
        self.label_inImage2.setGeometry(QtCore.QRect(80, 370, 200, 200))
        self.label_inImage2.setAutoFillBackground(False)
        self.label_inImage2.setText("")
        self.label_inImage2.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_inImage2.setScaledContents(True)
        self.label_inImage2.setObjectName("label_inImage2")
        self.listView_output2 = QtWidgets.QListView(self.tab_2)
        self.listView_output2.setGeometry(QtCore.QRect(580, 50, 161, 251))
        self.listView_output2.setObjectName("listView_output2")
        self.label_outImage2 = QtWidgets.QLabel(self.tab_2)
        self.label_outImage2.setGeometry(QtCore.QRect(560, 370, 200, 200))
        self.label_outImage2.setText("")
        self.label_outImage2.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_outImage2.setScaledContents(True)
        self.label_outImage2.setObjectName("label_outImage2")
        self.listView_input2 = QtWidgets.QListView(self.tab_2)
        self.listView_input2.setGeometry(QtCore.QRect(100, 50, 161, 251))
        self.listView_input2.setObjectName("listView_input2")
        self.pushButton_inOpen2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_inOpen2.setGeometry(QtCore.QRect(100, 310, 81, 28))
        self.pushButton_inOpen2.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                              "font: 75 9pt \"Arial\";\n"
                                              "color: rgb(7, 7, 7);")
        self.pushButton_inOpen2.setObjectName("pushButton_inOpen2")
        self.pushButton_inDelete2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_inDelete2.setGeometry(QtCore.QRect(180, 310, 81, 28))
        self.pushButton_inDelete2.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                                "font: 75 9pt \"Arial\";\n"
                                                "color: rgb(7, 7, 7);")
        self.pushButton_inDelete2.setObjectName("pushButton_inDelete2")
        self.pushButton_outSave2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_outSave2.setGeometry(QtCore.QRect(580, 310, 81, 28))
        self.pushButton_outSave2.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                               "font: 75 9pt \"Arial\";\n"
                                               "color: rgb(7, 7, 7);")
        self.pushButton_outSave2.setObjectName("pushButton_outSave2")
        self.pushButton_outDelete2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_outDelete2.setGeometry(QtCore.QRect(660, 310, 81, 28))
        self.pushButton_outDelete2.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                                 "font: 75 9pt \"Arial\";\n"
                                                 "color: rgb(7, 7, 7);")
        self.pushButton_outDelete2.setObjectName("pushButton_outDelete2")
        self.label_outResult2 = QtWidgets.QLabel(self.tab_2)
        self.label_outResult2.setGeometry(QtCore.QRect(160, 620, 531, 51))
        self.label_outResult2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_outResult2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "font: 75 14pt \"Arial\";")
        self.label_outResult2.setLineWidth(0)
        self.label_outResult2.setObjectName("label_outResult2")
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setGeometry(QtCore.QRect(100, 30, 101, 16))
        self.label_46.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_46.setObjectName("label_46")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(580, 30, 101, 16))
        self.label_9.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(370, 430, 81, 61))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(370, 140, 81, 61))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_inImage3 = QtWidgets.QLabel(self.tab_3)
        self.label_inImage3.setGeometry(QtCore.QRect(80, 370, 200, 200))
        self.label_inImage3.setAutoFillBackground(False)
        self.label_inImage3.setText("")
        self.label_inImage3.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_inImage3.setScaledContents(True)
        self.label_inImage3.setObjectName("label_inImage3")
        self.listView_output3 = QtWidgets.QListView(self.tab_3)
        self.listView_output3.setGeometry(QtCore.QRect(580, 50, 161, 251))
        self.listView_output3.setObjectName("listView_output3")
        self.label_outResult3_2 = QtWidgets.QLabel(self.tab_3)
        self.label_outResult3_2.setGeometry(QtCore.QRect(560, 370, 200, 200))
        self.label_outResult3_2.setText("")
        self.label_outResult3_2.setPixmap(QtGui.QPixmap("./image/back.png"))
        self.label_outResult3_2.setScaledContents(True)
        self.label_outResult3_2.setObjectName("label_outResult3_2")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(370, 140, 81, 61))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.listView_input3 = QtWidgets.QListView(self.tab_3)
        self.listView_input3.setGeometry(QtCore.QRect(100, 50, 161, 251))
        self.listView_input3.setObjectName("listView_input3")
        self.label_outResult3 = QtWidgets.QLabel(self.tab_3)
        self.label_outResult3.setGeometry(QtCore.QRect(160, 620, 531, 51))
        self.label_outResult3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_outResult3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "font: 75 14pt \"Arial\";")
        self.label_outResult3.setLineWidth(0)
        self.label_outResult3.setObjectName("label_outResult3")
        self.pushButton_detect3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_detect3.setGeometry(QtCore.QRect(370, 540, 93, 28))
        self.pushButton_detect3.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                              "font: 75 9pt \"Arial\";\n"
                                              "color: rgb(7, 7, 7);")
        self.pushButton_detect3.setObjectName("pushButton_detect3")
        self.pushButton_inOpen3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_inOpen3.setGeometry(QtCore.QRect(100, 310, 81, 28))
        self.pushButton_inOpen3.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                              "font: 75 9pt \"Arial\";\n"
                                              "color: rgb(7, 7, 7);")
        self.pushButton_inOpen3.setObjectName("pushButton_inOpen3")
        self.pushButton_inDelete3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_inDelete3.setGeometry(QtCore.QRect(180, 310, 81, 28))
        self.pushButton_inDelete3.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                                "font: 75 9pt \"Arial\";\n"
                                                "color: rgb(7, 7, 7);")
        self.pushButton_inDelete3.setObjectName("pushButton_inDelete3")
        self.pushButton_outDelete3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_outDelete3.setGeometry(QtCore.QRect(660, 310, 81, 28))
        self.pushButton_outDelete3.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                                 "font: 75 9pt \"Arial\";\n"
                                                 "color: rgb(7, 7, 7);")
        self.pushButton_outDelete3.setObjectName("pushButton_outDelete3")
        self.pushButton_outSave3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_outSave3.setGeometry(QtCore.QRect(580, 310, 81, 28))
        self.pushButton_outSave3.setStyleSheet("background-color :rgb(161, 161, 161);\n"
                                               "font: 75 9pt \"Arial\";\n"
                                               "color: rgb(7, 7, 7);")
        self.pushButton_outSave3.setObjectName("pushButton_outSave3")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(100, 30, 101, 16))
        self.label_47.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_47.setObjectName("label_47")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(580, 30, 101, 16))
        self.label_13.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(370, 430, 81, 61))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/newPrefix/detect.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.pushButton_outSave3.raise_()
        self.label_inImage3.raise_()
        self.listView_output3.raise_()
        self.label_outResult3_2.raise_()
        self.label_18.raise_()
        self.listView_input3.raise_()
        self.label_outResult3.raise_()
        self.pushButton_detect3.raise_()
        self.pushButton_inOpen3.raise_()
        self.pushButton_inDelete3.raise_()
        self.pushButton_outDelete3.raise_()
        self.label_47.raise_()
        self.label_13.raise_()
        self.label_19.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        GANgineer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GANgineer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        GANgineer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GANgineer)
        self.statusbar.setObjectName("statusbar")
        GANgineer.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(GANgineer)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(GANgineer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRecent = QtWidgets.QAction(GANgineer)
        self.actionRecent.setObjectName("actionRecent")
        self.actionSave = QtWidgets.QAction(GANgineer)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(GANgineer)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSave_All = QtWidgets.QAction(GANgineer)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionPring = QtWidgets.QAction(GANgineer)
        self.actionPring.setObjectName("actionPring")
        self.actionClose = QtWidgets.QAction(GANgineer)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(GANgineer)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtWidgets.QAction(GANgineer)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(GANgineer)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(GANgineer)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(GANgineer)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(GANgineer)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(GANgineer)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtWidgets.QAction(GANgineer)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionPreferences = QtWidgets.QAction(GANgineer)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionGAN = QtWidgets.QAction(GANgineer)
        self.actionGAN.setObjectName("actionGAN")
        self.actionAbout_GANgineer = QtWidgets.QAction(GANgineer)
        self.actionAbout_GANgineer.setObjectName("actionAbout_GANgineer")
        self.menu.addAction(self.actionUndo)
        self.menu.addAction(self.actionRedo)
        self.menu.addSeparator()
        self.menu.addAction(self.actionCut)
        self.menu.addAction(self.actionCopy)
        self.menu.addAction(self.actionPaste)
        self.menu.addAction(self.actionDelete)
        self.menu.addAction(self.actionSelect_All)
        self.menu_2.addAction(self.actionPreferences)
        self.menu_3.addAction(self.actionNew)
        self.menu_3.addAction(self.actionOpen)
        self.menu_3.addAction(self.actionRecent)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionSave)
        self.menu_3.addAction(self.actionSave_As)
        self.menu_3.addAction(self.actionSave_All)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionPring)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionClose)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionGAN)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_GANgineer)
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(GANgineer)
        self.tabWidget.setCurrentIndex(2)
        self.pushButton_detect3.clicked.connect(GANgineer.detectEvent3)
        self.pushButton_inOpen3.clicked.connect(GANgineer.inOpen3)
        self.pushButton_inDelete3.clicked.connect(GANgineer.listDelete3)
        self.pushButton_outDelete3.clicked.connect(GANgineer.listDelete3)
        self.pushButton_outSave3.clicked.connect(GANgineer.outSave3)
        self.pushButton_inOpen2.clicked.connect(GANgineer.inOpen2)
        self.pushButton_inDelete2.clicked.connect(GANgineer.listDelete2)
        self.pushButton_outSave2.clicked.connect(GANgineer.outSave2)
        self.pushButton_outDelete2.clicked.connect(GANgineer.listDelete2)
        self.pushButton_detect2.clicked.connect(GANgineer.detectEvent2)
        self.pushButton_inOpen.clicked.connect(GANgineer.inOpen)
        self.pushButton_inDelete.clicked.connect(GANgineer.listDelete)
        self.pushButton_outSave.clicked.connect(GANgineer.outSave)
        self.pushButton_outDelete.clicked.connect(GANgineer.listDelete)
        self.pushButton_detect.clicked.connect(GANgineer.detectEvent)

        self.pbar = QProgressBar(self.tab)
        self.pbar.setGeometry(310, 580, 231, 23)
        self.pbar2 = QProgressBar(self.tab_2)
        self.pbar2.setGeometry(310, 580, 231, 23)
        self.pbar3 = QProgressBar(self.tab_3)
        self.pbar3.setGeometry(310, 580, 231, 23)

        QtCore.QMetaObject.connectSlotsByName(GANgineer)

        self.listView_input.clicked.connect(GANgineer.listClicked)
        self.listView_output.clicked.connect(GANgineer.listClicked2)

    timer = QBasicTimer()
    step = 0
    fileName1 = []
    flag_num = 0




    list_steelout_dir = ["./image/steeloutput/1.png",
                         "./image/steeloutput/2.png", "./image/steeloutput/3.png",
                         "./image/steeloutput/4.png", "./image/steeloutput/5.png",
                         "./image/steeloutput/6.png"]
    list_steelout_per = [0.50732422, 0.5480957, 0.30761719, 0.37475586, 0.51123047, 0.54150391]
    list_steelout_per2 = [252, 301, 218, 226, 275, 283]

    list_steelout = ["1_out.png", "2_out.png", "3_out.png", "4_out.png", "5_out.png", "6_out.png"]



    def timerEvent(self, e):
        if self.step >= 100 and self.flag_num == 1:
            self.timer.stop()
            listView = self.listView_output
            model = QStandardItemModel()
            for v in self.list_steelout:
                model.appendRow(QStandardItem(v))
            listView.setModel(model)
            return

        self.step = self.step + 1
        self.pbar.setValue(self.step)

    def doAction(self):
        self.step = 0
        self.flag_num = 1
        self.pbar.setValue(0)
        if self.timer.isActive():
            self.timer.stop()
        else:
            self.timer.start(100, self)

    def doAction2(self):
        self.step = 0
        self.flag_num = 2
        self.pbar2.setValue(0)
        if self.timer.isActive():
            self.timer.stop()
        else:
            self.timer.start(100, self)

    def doAction3(self):
        self.step = 0
        self.flag_num = 3
        self.pbar3.setValue(0)
        if self.timer.isActive():
            self.timer.stop()
        else:
            self.timer.start(100, self)

    def listClicked(self):
        row = self.listView_input.currentIndex()
        if self.fileName1:
            print(self.fileName1)
            print(row.row())
        else:
            print("No")
        self.label_inImage.setPixmap(QtGui.QPixmap(self.fileName1[row.row()]))


    def listClicked2(self):
        row = self.listView_output.currentIndex()
        print(row.row())
        self.label_outImage.setPixmap(QtGui.QPixmap(self.list_steelout_dir[row.row()]))
        self.label_inImage.setPixmap(QtGui.QPixmap(self.fileName1[row.row()]))
        self.label_outResult.setText("분율: {0}%\t\t경도: {1}HV".format(round(self.list_steelout_per[row.row()]*100,4),self.list_steelout_per2[row.row()]))

    def detectEvent(self):

        self.doAction()

    def inOpen(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.fileName1, _ = QFileDialog.getOpenFileNames(self, "이미지파일 불러오기", "",
                                                         "All Files (*);;Python Files (*.py)", options=options)
        listView = self.listView_input
        model = QStandardItemModel()

        if self.fileName1:
            print(self.fileName1, "check")
        for v in self.fileName1:
            model.appendRow(QStandardItem(str(v.split("/")[-1:][0])))
        listView.setModel(model)

    def listDelete(self):
        pass

    def outSave(self):
        pass

    def detectEvent2(self):
        self.doAction2()

    def inOpen2(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.fileName1, _ = QFileDialog.getOpenFileNames(self, "이미지파일 불러오기", "",
                                                   "All Files (*);;Python Files (*.py)", options=options)
        listView = self.listView_input2
        model = QStandardItemModel()

        if self.fileName1:
            print(self.fileName1)
        for v in self.fileName1:
            model.appendRow(QStandardItem(str(v.split("/")[-1:][0])))
            # print(str(v.split("/")[-1:][0]))
        listView.setModel(model)

    def listDelete2(self):
        pass

    def outSave2(self):
        pass

    def detectEvent3(self):
        self.doAction3()

    def inOpen3(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.fileName1, _ = QFileDialog.getOpenFileNames(self, "이미지파일 불러오기", "",
                                                   "All Files (*);;Python Files (*.py)", options=options)
        listView = self.listView_input3
        model = QStandardItemModel()

        if self.fileName1:
            print(self.fileName1)
        for v in self.fileName1:
            model.appendRow(QStandardItem(str(v.split("/")[-1:][0])))
            # print(str(v.split("/")[-1:][0]))
        listView.setModel(model)

    def listDelete3(self):
        pass

    def outSave3(self):
        pass

    def retranslateUi(self, GANgineer):
        _translate = QtCore.QCoreApplication.translate
        GANgineer.setWindowTitle(_translate("GANgineer", "GANgineer"))
        self.label_outResult.setText(
            _translate("GANgineer", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_detect.setText(_translate("GANgineer", "Detect"))
        self.pushButton_inOpen.setText(_translate("GANgineer", "열기"))
        self.pushButton_inDelete.setText(_translate("GANgineer", "삭제"))
        self.pushButton_outDelete.setText(_translate("GANgineer", "삭제"))
        self.pushButton_outSave.setText(_translate("GANgineer", "저장"))
        self.label_4.setText(_translate("GANgineer",
                                        "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Output Data</span></p></body></html>"))
        self.label_45.setText(_translate("GANgineer",
                                         "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Input Data</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GANgineer", "Steel"))
        self.pushButton_detect2.setText(_translate("GANgineer", "Detect"))
        self.pushButton_inOpen2.setText(_translate("GANgineer", "열기"))
        self.pushButton_inDelete2.setText(_translate("GANgineer", "삭제"))
        self.pushButton_outSave2.setText(_translate("GANgineer", "저장"))
        self.pushButton_outDelete2.setText(_translate("GANgineer", "삭제"))
        self.label_outResult2.setText(
            _translate("GANgineer", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_46.setText(_translate("GANgineer",
                                         "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Input Data</span></p></body></html>"))
        self.label_9.setText(_translate("GANgineer",
                                        "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Output Data</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GANgineer", "CFRP"))
        self.label_outResult3.setText(
            _translate("GANgineer", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_detect3.setText(_translate("GANgineer", "Detect"))
        self.pushButton_inOpen3.setText(_translate("GANgineer", "열기"))
        self.pushButton_inDelete3.setText(_translate("GANgineer", "삭제"))
        self.pushButton_outDelete3.setText(_translate("GANgineer", "삭제"))
        self.pushButton_outSave3.setText(_translate("GANgineer", "저장"))
        self.label_47.setText(_translate("GANgineer",
                                         "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Input Data</span></p></body></html>"))
        self.label_13.setText(_translate("GANgineer",
                                         "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Output Data</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("GANgineer", "Ti64"))
        self.menu.setTitle(_translate("GANgineer", "Edit"))
        self.menu_2.setTitle(_translate("GANgineer", "Settings"))
        self.menu_3.setTitle(_translate("GANgineer", "File"))
        self.menuHelp.setTitle(_translate("GANgineer", "Help"))
        self.actionNew.setText(_translate("GANgineer", "New"))
        self.actionOpen.setText(_translate("GANgineer", "Open"))
        self.actionRecent.setText(_translate("GANgineer", "Recent"))
        self.actionSave.setText(_translate("GANgineer", "Save"))
        self.actionSave_As.setText(_translate("GANgineer", "Save As"))
        self.actionSave_All.setText(_translate("GANgineer", "Save All"))
        self.actionPring.setText(_translate("GANgineer", "Print"))
        self.actionClose.setText(_translate("GANgineer", "Close"))
        self.actionQuit.setText(_translate("GANgineer", "Quit"))
        self.actionUndo.setText(_translate("GANgineer", "Undo"))
        self.actionRedo.setText(_translate("GANgineer", "Redo"))
        self.actionCut.setText(_translate("GANgineer", "Cut"))
        self.actionCopy.setText(_translate("GANgineer", "Copy"))
        self.actionPaste.setText(_translate("GANgineer", "Paste"))
        self.actionDelete.setText(_translate("GANgineer", "Delete"))
        self.actionSelect_All.setText(_translate("GANgineer", "Select All"))
        self.actionPreferences.setText(_translate("GANgineer", "Preferences"))
        self.actionGAN.setText(_translate("GANgineer", "GANgineer Help"))
        self.actionAbout_GANgineer.setText(_translate("GANgineer", "About GANgineer"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    GANgineer = QtWidgets.QMainWindow()
    ui = Ui_GANgineer()
    ui.setupUi(GANgineer)
    GANgineer.show()
    sys.exit(app.exec_())
